INSERT INTO core.del_stavbe (
posel_id, 
sifra_ko,
ime_ko, 
obcina, 
stevilka_stavbe,
stevilka_dela_stavbe,
naselje, 
ulica, 
hisna_stevilka, 
dodatek_hs,
stev_stanovanja, 
opremljenost,
dejanska_raba,
lega_dela_stavbe,
povrsina, 
povrsina_uporabna, 
coordinates, 
leto,
vrsta_prostorov_code, 
vrsta_prostorov_desc
)
SELECT
d.id_posla,
d.sifra_ko,
d.ime_ko,
d.obcina,
d.stevilka_stavbe,
d.stevilka_dela_stavbe,
d.naselje,
d.ulica,
d.hisna_stevilka,
d.dodatek_hs,
d.stevilka_stanovanja_ali_poslovnega_prostora,
d.opremljenost_oddanih_prostorov,
d.dejanska_raba_dela_stavbe,
d.lega_dela_stavbe_v_stavbi,
d.povrsina_dela_stavbe,
d.uporabna_povrsina_dela_stavbe,
ST_Transform(ST_SetSRID(ST_MakePoint(d.e_centroid, d.n_centroid), 3794), 4326),
d.leto,
d.vrsta_oddanih_prostorov,
s1.opis
FROM staging.del_stavbe d
LEFT JOIN staging.sifranti s1 ON s1.sifrant='Vrsta oddanih prostorov' AND s1.numericna_vrednost::integer = d.vrsta_oddanih_prostorov
WHERE d.vrsta_oddanih_prostorov IN (1, 2)