INSERT INTO core.kpp_del_stavbe (
    posel_id,
    sifra_ko,
    ime_ko,
    obcina,
    stevilka_stavbe,
    stevilka_dela_stavbe,
    naselje,
    ulica,
    hisna_stevilka,
    dodatek_hs,
    stev_stanovanja,
    vrsta,
    leto_izgradnje_dela_stavbe,
    stavba_je_dokoncana,
    gradbena_faza,
    novogradnja,
    prodana_povrsina,
    prodani_delez,
    prodana_povrsina_dela_stavbe,
    prodana_uporabna_povrsina_dela_stavbe,
    nadstropje,
    stevilo_zunanjih_parkirnih_mest,
    atrij,
    povrsina_atrija,
    opombe,
    dejanska_raba,
    lega_v_stavbi,
    stevilo_sob,
    povrsina,
    povrsina_uporabna,
    prostori,
    pogodbena_cena,
    stopnja_ddv,
    coordinates,
    leto
)
SELECT
    id_posla,
    sifra_ko,
    ime_ko,
    obcina,
    stevilka_stavbe,
    stevilka_dela_stavbe,
    naselje,
    ulica,
    hisna_stevilka,
    dodatek_hs,
    stevilka_stanovanja_ali_poslovnega_prostora,
    vrsta_dela_stavbe,
    leto_izgradnje_dela_stavbe,
    stavba_je_dokoncana,
    gradbena_faza,
    novogradnja,
    prodana_povrsina,
    prodani_delez_dela_stavbe,
    prodana_povrsina_dela_stavbe,
    prodana_uporabna_povrsina_dela_stavbe,
    nadstropje_dela_stavbe,
    stevilo_zunanjih_parkirnih_mest,
    atrij,
    povrsina_atrija,
    opombe_o_nepremicnini,
    dejanska_raba_dela_stavbe,
    lega_dela_stavbe_v_stavbi,
    stevilo_sob,
    povrsina_dela_stavbe,
    uporabna_povrsina,
    prostori_dela_stavbe,
    pogodbena_cena_dela_stavbe,
    stopnja_ddv_dela_stavbe,
    -- Convert Slovenian coordinate system (D48/GK) to WGS84
    ST_Transform(ST_SetSRID(ST_MakePoint(e_centroid, n_centroid), 3794), 4326),
    leto
FROM staging.kpp_del_stavbe
-- WHERE d.vrsta_dela_stavbe IN (1, 2) AND sifra_ko IS NOT NULL AND posel_id IS NOT NULL
WHERE sifra_ko IS NOT NULL;

