INSERT INTO core.posel (
posel_id,
vrsta_posla_code,
vrsta_posla_desc,
datum_uveljavitve,
datum_sklenitve,
najemnina,
vkljuceno_stroski,
vkljuceno_ddv,
stopnja_ddv,
datum_zacetka_najemanja,
datum_prenehanja_najemanja,
cas_najemanja,
trajanje_najemanja,
opombe,
posredovanje_agencije,
trznost_posla_code,
trznost_posla_desc,
vrsta_akta_code,
vrsta_akta_desc,
datum_zadnje_spremembe,
datum_zadnje_uveljavitve,
leto
)
SELECT
p.id_posla,
p.vrsta_najemnega_posla,
s1.opis,
TO_DATE(p.datum_uveljavitve, 'DD.MM.YYYY'),
TO_DATE(p.datum_sklenitve_pogodbe, 'DD.MM.YYYY'),
p.pogodbena_najemnina,
CASE WHEN p.vkljucenost_obratovalnih_stroskov_v_najemnino = 1 THEN TRUE ELSE FALSE END,
CASE WHEN p.vkljucenost_ddv = 1 THEN TRUE ELSE FALSE END,
p.stopnja_ddv,
TO_DATE(p.datum_zacetka_najema, 'DD.MM.YYYY'),
TO_DATE(NULLIF(p.datum_prenehanja_najema, ''), 'DD.MM.YYYY'),
p.cas_najema,
p.trajanje_najema,
p.opombe_o_pravnem_poslu,
p.posredovanje_nepremicninske_agencije,
p.trznost_posla,
s3.opis,
p.vrsta_akta,
s4.opis,
TO_DATE(p.datum_zadnje_spremembe_posla, 'DD.MM.YYYY'),
TO_DATE(p.datum_zadnje_uveljavitve_posla, 'DD.MM.YYYY'),
p.leto
FROM staging.posel p
LEFT JOIN staging.sifranti s1 ON s1.sifrant='Vrsta najemnega posla' AND s1.numericna_vrednost::integer = p.vrsta_najemnega_posla
LEFT JOIN staging.sifranti s3 ON s3.sifrant='Tržnost posla' AND s3.numericna_vrednost::integer = p.trznost_posla
LEFT JOIN staging.sifranti s4 ON s4.sifrant='Vrsta akta' AND s4.numericna_vrednost::integer = p.vrsta_akta