services:
  db:
    build: .
    container_name: domogled-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: domogled
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data/raw_csvs:/var/lib/postgresql/csv_data
    ports:
      - "5432:5432"

volumes:
  db_data:
    external: true
    name: diplomski-projekt-domogled_db_data
